webapp/models/favourite_list.py
from sqlalchemy import PrimaryKeyConstraint
from .. import db


class FavouriteList(db.Model):
    __tablename__ = 'favourite_list'

    user_id = db.Column(db.String(250), db.ForeignKey('users.id', ondelete='CASCADE'))
    book_isbn = db.Column(db.String(30), db.ForeignKey('books.isbn', ondelete='CASCADE'))

    __table_args__ = (
        PrimaryKeyConstraint(
            user_id,
            book_isbn),
        {})

    cascade = "all, delete"

    def __init__(self, user_id, book_isbn):
        self.user_id = user_id
        self.book_isbn = book_isbn

webapp/views/accounts.py
from flask import Blueprint, flash, render_template, redirect, request, url_for, make_response
from flask_login import login_required, login_user, logout_user, current_user

from .. import bcrypt, db
from webapp.models.user_model import User
from webapp.form import LoginForm, RegisterForm
from ..models.book_model import Book
from ..models.favourite_list import FavouriteList

accounts_bp = Blueprint("accounts", __name__)


@accounts_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in.", "info")
        return redirect(url_for("home.home"))
    form = LoginForm(request.form)

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        user = User.query.filter_by(email=email).first()
        if user and bcrypt.check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for("home.home"))
        flash("Invalid email and/or password.", "danger")

    return render_template("accounts/login.html", form=form)


@accounts_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        flash("You are already registered.", "info")
        return redirect(url_for("home.home"))
    form = RegisterForm(request.form)

    if form.validate_on_submit():
        user = User(full_name=form.fullname.data, username=form.username.data,
                    email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()

        login_user(user)
        flash("You registered and are now logged in. Welcome!", "success")

        return redirect(url_for("home.home"))

    return render_template("accounts/register.html", form=form)


@accounts_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out.", "success")
    return redirect(url_for("accounts.login"))


@accounts_bp.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    is_logged_in = current_user.is_authenticated
    if is_logged_in:
        return render_template("accounts/user_profile.html", is_logged_in=is_logged_in, user=current_user)


@accounts_bp.route("/update-profile", methods=["GET", "PATCH"])
@login_required
def update_profile():
    is_logged_in = current_user.is_authenticated

    if request.method == "GET" and is_logged_in:
        edit_status = request.args.get("edit") == "true"
        name = request.args.get("name")
        if edit_status:
            return render_template("accounts/edit_form.html", user=current_user, name=name)

        return render_template("accounts/cancel_edit_form.html", user=current_user, name=name)

    if request.method == "PATCH" and is_logged_in:
        name = request.args.get("name")
        email = request.form.get("email")
        full_name = request.form.get("fullname")
        username = request.form.get("username")

        user = User.query.filter_by(id=current_user.id).first()

        email = email if email else user.email
        full_name = full_name if full_name else user.full_name
        username = username if username else user.username

        user.email = email
        user.full_name = full_name
        user.username = username

        db.session.commit()

        user = User.query.filter_by(id=current_user.id).first()
        return render_template("accounts/cancel_edit_form.html", user=user, name=name)


@accounts_bp.route("/favourite-list", methods=["GET"])
@login_required
def favourite_list():
    is_logged_in = current_user.is_authenticated
    if is_logged_in:
        book_isbn_list = FavouriteList.query.with_entities(FavouriteList.book_isbn).filter_by(user_id=current_user.id)
        fav_list = Book.query.filter(Book.isbn.in_(book_isbn_list)).all()
        subtotal = sum(book.price for book in fav_list)
        return render_template("accounts/favourite_list.html",
                               is_logged_in=is_logged_in,
                               favourite_list=fav_list,
                               subtotal_price=subtotal)
    return redirect(url_for("home.login"))


@accounts_bp.route("/add-to-favourite", methods=["POST"])
@login_required
def add_to_favourite():
    is_logged_in = current_user.is_authenticated
    if is_logged_in:
        book_isbn = request.args.get("isbn")
        existing_book_isbn = FavouriteList.query.filter_by(book_isbn=book_isbn).first()
        if existing_book_isbn is not None:
            success = False
            return render_template("accounts/add_to_favourite_response.html", success=success)
        fav_item = FavouriteList(user_id=current_user.id, book_isbn=book_isbn)
        db.session.add(fav_item)
        db.session.commit()
        success = True

        return render_template("accounts/add_to_favourite_response.html", success=success)
    return redirect(url_for("accounts.login"))


@accounts_bp.route("/delete-from-favorite/<string:isbn>", methods=["DELETE"])
@login_required
def delete_from_favourite(isbn):
    is_logged_in = current_user.is_authenticated
    if is_logged_in:
        FavouriteList.query.filter(FavouriteList.book_isbn == isbn).delete()
        db.session.commit()

        book_isbn_list = FavouriteList.query.with_entities(FavouriteList.book_isbn).filter_by(user_id=current_user.id)
        fav_list = Book.query.filter(Book.isbn.in_(book_isbn_list)).all()

        return render_template("accounts/favourite_list_inner.html", favourite_list=fav_list)

    return render_template("errors/400.html")


@accounts_bp.route("/favourite-list-summary", methods=["GET"])
@login_required
def favourite_list_summary():
    is_logged_in = current_user.is_authenticated
    if is_logged_in:
        # Query to fetch the list of ISBNs in the user's favorites.
        book_isbn_list = FavouriteList.query.with_entities(FavouriteList.book_isbn). \
            filter_by(user_id=current_user.id).all()
        isbn_list = [isbn for (isbn,) in book_isbn_list]
        # Query to get all books that are in the favorites list.
        if isbn_list:
            fav_list = Book.query.filter(Book.isbn.in_(isbn_list)).all()
        else:
            fav_list = []

        total_item = len(fav_list)
        total_price = sum(book.price for book in fav_list)

        html_content = render_template("accounts/favourite_list_summary.html",
                                       total_item=total_item, total_price=total_price)
        return html_content
    else:
        return render_template("errors/400.html"), 400

webapp/views/home.py
import pandas as pd
from flask import Blueprint, redirect, render_template, request, url_for, abort
from flask_login import current_user, login_required
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, LongType
from webapp import db
from webapp.models.book_model import Book, OpentrolleyBook, LazadaBook, NewArrival
import torch
from webapp.models.favourite_list import FavouriteList
from webapp.models.rating import Interaction, Rating
from webapp.models.review import Review
from webapp.models.user_model import User
from webapp.recommender.content_based_model import get_recommendations
from webapp.recommender.model import model, item_id_map, original_book_data, user_item_df, user_id_map
from webapp.recommender.utils import inference
from pyspark.ml.recommendation import ALS, ALSModel

home_bp = Blueprint("home", __name__)

spark = SparkSession.builder \
    .appName("Book Recommender") \
    .master("local[*]") \
    .config("spark.driver.memory", "1g") \
    .config("spark.driver.memoryOverhead", "512m") \
    .config("spark.memory.fraction", "0.8") \
    .config("spark.default.parallelism", "200") \
    .config("spark.sql.shuffle.partitions", "200") \
    .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer") \
    .getOrCreate()


@home_bp.route("/", methods=["GET"])
def home():
    if not current_user.is_authenticated:
        return redirect(url_for("home.landing_page"))

    if current_user.is_admin:
        return redirect(url_for("admin.admin"))

    page = request.args.get("page")
    sort_by = request.args.get("sort")
    if not page or not page.isdigit():
        return redirect(url_for("home.home", page=1))

    page = int(page)

    if sort_by == "newest":
        books = Book.query.order_by(Book.publication_year.desc()).limit(350).all()
    elif sort_by == "price-asc":
        books = Book.query.order_by(Book.price).limit(350).all()
    elif sort_by == "price-desc":
        books = Book.query.order_by(Book.price.desc()).limit(350).all()
    else:
        books = Book.query.order_by(Book.average_rating.desc()).limit(350).all()

    book_isbn_list = FavouriteList.query.with_entities(FavouriteList.book_isbn).filter_by(user_id=current_user.id)
    fav_list = Book.query.filter(Book.isbn.in_(book_isbn_list)).all()
    total_item = len(fav_list)
    total_price = sum([b.price for b in fav_list])

    books = books[(50 * page - 50): (50 * page)]

    return render_template(
        "home.html",
        is_logged_in=True,
        books=books,
        page=page,
        total_item=total_item,
        total_price=total_price,
        username=current_user.username
    )


@home_bp.route("/home", methods=["GET"])
def landing_page():
    new_arrivals = NewArrival.query.order_by(NewArrival.publication_year.desc()).limit(5).all()
    return render_template("components/landing_page.html", new_arrivals=new_arrivals)


@home_bp.route("/about", methods=["GET"])
def about():
    if current_user.is_authenticated:
        is_logged_in = current_user.is_authenticated
        username = current_user.username
        return render_template("about.html", is_logged_in=is_logged_in, username=username)
    return render_template("about.html", is_logged_in=False)


@home_bp.route("/book/<string:isbn>", methods=["GET"])
@login_required
def book(isbn):
    if not current_user.is_authenticated:
        return redirect(url_for("home.landing_page"))

    current_book = Book.query.filter(Book.isbn.in_([isbn])).first()
    if current_book is None:
        return render_template("errors/404.html")

    is_logged_in = True

    db_user_id = current_user.user_id
    user_id = torch.LongTensor([db_user_id])
    total_books = Book.query.count()

    # Million dollars recommender inference =))
    insert_interaction(current_user.id, isbn)

    # ratings = Rating.query.filter_by(user_id=current_user.id).all()
    book_exist_in_rating = Rating.query.filter_by(book_isbn=isbn, user_id=current_user.id).first()
    if book_exist_in_rating:
        rated = True
    else:
        rated = False

    current_user_id_in_df = user_id_map.get(db_user_id, 35)
    try:
        als_model = ALSModel.load(f"users/{current_user.user_id}/model.als")
    except Exception as e:
        print("Error loading the ALS model:", e)
        als_model = None
    recommend_books_als = None
    if als_model is not None:
        mylist = [{"user": current_user_id_in_df}]
        schema = StructType([
            StructField("user", LongType(), True)
        ])

        # Create the DataFrame using the list of dictionaries and the defined schema
        user_df = spark.createDataFrame(mylist, schema=schema)
        user_recs = als_model.recommendForUserSubset(user_df, 20)
        item_df = user_recs.selectExpr("user", "explode(recommendations) as rec")
        items = item_df.select("rec.item", "rec.rating")
        unique_items_list = [row['item'] for row in items.select("item").distinct().collect()]
        print(unique_items_list)
        top_k_books_isbn = original_book_data[original_book_data.book_id.isin(unique_items_list)]["isbn"].tolist()
        recommend_books_als = Book.query.filter(Book.isbn.in_(top_k_books_isbn)).all()

    updated_ratings = [0] * total_books

    # Query all interactions for the user
    interactions = Interaction.query.filter_by(user_id=current_user.id).all()
    # Get all ISBNs the user has interacted with
    interacted_isbns = [interaction.book_isbn for interaction in interactions]

    # Update ratings based on the interactions
    for i in interacted_isbns:
        if i in original_book_data['isbn'].values:
            book_id = original_book_data[original_book_data["isbn"] == i]["book_id"].to_list()
            if book_id:
                book_index = item_id_map.get(book_id[0], None)
                if book_index is not None:
                    updated_ratings[book_index] = 1

    user_ratings_tensor = torch.FloatTensor([updated_ratings])
    recommend_books = inference(
        model,
        user_id=user_id,
        user_ratings_tensor=user_ratings_tensor,
        item_id_map=item_id_map,
        apply_dropout=True,
    )

    recommend_books = Book.query.filter(Book.isbn.in_(recommend_books)).all()

    opentrolley_book = OpentrolleyBook.query.filter_by(isbn=current_book.isbn).first()
    lazada_book = LazadaBook.query.filter(LazadaBook.isbn.in_([isbn])).first()

    book_isbn_list = FavouriteList.query.with_entities(FavouriteList.book_isbn).filter_by(user_id=current_user.id)
    fav_list = Book.query.filter(Book.isbn.in_(book_isbn_list)).all()
    total_item = len(fav_list)
    total_price = sum([b.price for b in fav_list])

    reviews = (
        db.session.query(Review, User)
        .join(User, Review.user_id == User.id)
        .filter(Review.book_isbn == isbn)
        .all()
    )
    content_based_isbn_list = get_recommendations(current_book.title, 20)
    if content_based_isbn_list is None or len(content_based_isbn_list) is None:
        content_based_isbn_list = []
    similar_books = Book.query.filter(Book.isbn.in_(content_based_isbn_list)).all()
    return render_template("book_details.html",
                           book=current_book,
                           recommend_books=recommend_books,
                           similar_books=similar_books,
                           opentrolley_book=opentrolley_book,
                           lazada_book=lazada_book,
                           is_logged_in=is_logged_in,
                           total_item=total_item,
                           total_price=total_price, username=current_user.username,
                           reviews=reviews,
                           rated=rated,
                           recommend_books_als=recommend_books_als)


def insert_interaction(user_id, book_isbn):
    new_interaction = Interaction(user_id=user_id, book_isbn=book_isbn)
    db.session.add(new_interaction)
    try:
        db.session.commit()
        print("Data inserted successfully!")
    except Exception as e:
        db.session.rollback()
        print(f"An error occurred: {e}")


@home_bp.route("/rates/<string:isbn>", methods=["POST"])
@login_required
def rating_book(isbn):
    rating = request.form["rating"]
    rating = int(rating)
    new_rating = Rating(user_id=current_user.id, book_isbn=isbn, rating=rating)
    db.session.add(new_rating)
    try:
        current_user_id_in_df = user_id_map.get(current_user.user_id, 35)
        db.session.commit()
        print("Data inserted successfully!")
        # Check if the book is already rated by the user
        ratings = get_user_ratings(current_user.id)
        # Update user-item DataFrame only if necessary
        if len(ratings) % 5 == 0:
            # Query all interactions for the user
            # Get all ISBNs the user has interacted with
            interacted_isbns = [rating.book_isbn for rating in ratings]
            rating_values = [rating.rating for rating in ratings]

            # Update ratings based on the interactions
            books_id = []
            for isbn in interacted_isbns:
                if isbn in original_book_data['isbn'].values:
                    book_id = original_book_data[original_book_data["isbn"] == isbn]["book_id"].to_list()
                    if book_id:
                        book_index = item_id_map.get(book_id[0], None)
                        if book_index is not None:
                            books_id.append(book_index)
            new_user_ratings = {
                'user': [current_user_id_in_df] * len(rating_values),
                'item': books_id,
                'rating': rating_values
            }
            temp_df = user_item_df[user_item_df['user'] != current_user_id_in_df]

            updated_user_item_df = pd.concat([temp_df, pd.DataFrame(new_user_ratings)], ignore_index=True)
            updated_user_item_df['user'] = updated_user_item_df['user'].astype(int)

webapp/views/image.py
import base64
import io
import os
from PIL import Image
from flask import Blueprint, send_file, abort

image_bp = Blueprint('image', __name__)
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../'))


@image_bp.route('/images/<string:isbn>', methods=['GET'])
def get_image(isbn):
    # image = Image.open("./images/" + isbn + ".png")
    # data = io.BytesIO()
    # image.save(data, "PNG")
    # encoded_img_data = base64.b64encode(data.getvalue())
    # print(encoded_img_data)
    image_path = os.path.join(BASE_DIR, 'images', f'{isbn}.png')
    if not os.path.exists(image_path):
        abort(404)
    return send_file(image_path, mimetype='image/png')

webapp/templates/components/cart.html
<details class="dropdown dropdown-end mr-3 mt-3 cursor-pointer relative z-50" hx-ext="multi-swap">
    <summary class="mb-2.5" 
             hx-get="{{ url_for('accounts.favourite_list_summary') }}"
             hx-swap="outerHTML"
             hx-target="#summary-content"
             hx-trigger="click">
        <img width="36" height="36" src="{{ url_for('static', filename='images/heart.png') }}" alt="Heart Icon"/>
    </summary>
    <div id="summary-content" class="mt-3 pr-3 card card-compact dropdown-content w-52 text-gray-800 bg-white/60 shadow-lg ring-1
                    ring-black/5 isolate backdrop-blur-xl relative z-20">
        <div class="card-body relative z-20 rounded-md">
            <span class="font-bold text-lg" id="id1">{{ total_item }} books</span>
            <span class="text-info" id="id2">S${{ total_price }}</span>
            <div class="card-actions">
                <a class="btn bg-teal-600 hover:bg-teal-800 text-white btn-block border-0"
                   href="{{ url_for('accounts.favourite_list') }}">
                    View details</a>
            </div>
        </div>
    </div>
</details>

webapp/templates/components/products.html
<div class="bg-white">
    <div class="mx-auto max-w-2xl px-4 py-12 sm:px-6 lg:max-w-7xl lg:px-8">
      <div class="flex flex-row items-center justify-center pb-2 relative">
        <h2 class="text-md md:text-lg lg:text-xl flex-1 font-semibold">Books</h2>
      <style>
          #sortbox:checked ~ #sort-box-menu {
              opacity: 1;
          }
      </style>

      <div class="relative justify-end z-20">
          <input type="checkbox" id="sortbox" class="hidden absolute">
          <label for="sortbox" class="flex items-center space-x-1 cursor-pointer text-gray-500 hover:text-black ">
          <span class="text-md">sort by</span>
          <svg class="h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
              </svg>
          </label>

              <div id="sort-box-menu" class="absolute mt-1 right-1 top-full min-w-max shadow opacity-0 z-10">
              <ul class="block text-right text-gray-800 bg-white/85 shadow-lg ring-1 ring-black/5 isolate backdrop-blur-xl rounded-md">
                  <li><a href="{{ url_for("home.home", page=page, sort="newest") }}" class="block px-3 py-2 hover:bg-gray-200">Newest</a></li>
                  <li><a href="{{ url_for("home.home", page=page, sort="rating") }}" class="block px-3 py-2 hover:bg-gray-200">Rating</a></li>
                  <li><a href="{{ url_for("home.home", page=page, sort="price-asc") }}" class="block px-3 py-2 hover:bg-gray-200">Price: Low to High</a></li>
                  <li><a href="{{ url_for("home.home", page=page, sort="price-desc") }}" class="block px-3 py-2 hover:bg-gray-200">Price: High to Low</a></li>
                  <li><a href="{{ url_for("home.home", page=page) }}" class="block px-3 py-2 hover:bg-gray-200">None</a></li>
              </ul>
          </div>
      </div>
    </div>
      <div class="grid grid-cols-2 gap-x-6 gap-y-10 sm:grid-cols-4 xl:grid-cols-5 xl:gap-x-8">
        {% for book in books %}
        <a href="{{ url_for('home.book', isbn=book.isbn) }}" class="group">
          <div class="relative w-full h-64 sm:h-72 overflow-hidden rounded-md bg-transparent border-gray-600 xl:aspect-h-8 xl:aspect-w-7">
            <div class="absolute inset-0 bg-gray-200 opacity-40 group-hover:opacity-90"></div>
            <img src="{{ url_for("image.get_image", isbn=book.isbn) }}"
                 alt="image"
                 class="relative z-10 object-contain w-full h-full object-center pt-2 px-2 md:pt-6 md:px-4">
          </div>

          <h3 class="mt-4 text-base text-cyan-700 hover:underline hover:text-cyan-900 hover:cursor-pointer line-clamp-2">{{ book.title }}</h3>
          <p class="mt-1 text-sm font-medium text-gray-900">by <i>{{ book.author}}</i> ({{ book.publication_year }})</p>
          <p class="mt-1 text-sm font-medium text-gray-900 flex flex-row -ml-1">
              {% for i in range(1, 6) %}
                {% if i < book.average_rating %}
                     <svg class="w-3 h-3 ms-1 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                        fill="currentColor" viewBox="0 0 22 20">
                        <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"></path>
                    </svg>
                {% else %}
                        <svg class="w-3 h-3 ms-1 text-gray-300 dark:text-gray-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                            <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"></path>
                        </svg>
                {% endif %}
            {% endfor %}
          </p>
          <p class="mt-1 text-base font-medium text-gray-950">S${{ book.price }}</p>
        </a>
        {% endfor %}
      </div>
    </div>
</div>

webapp/templates/components/rating_form.html
<!-- Open the modal using ID.showModal() method -->
<button class="btn btn-active btn-link" onclick="my_modal_1.showModal()">Rate</button>
<dialog id="my_modal_1" class="modal">
    <div class="modal-box">
        <div class="modal-action" style="margin-top: 0.5rem;">
            <form method="dialog">
                <button class=""><i class="fa-solid fa-xmark"></i></button>
            </form>
        </div>
        <h3 class="font-semibold text-sm ml-1">Rate this book!</h3>
        <form id="model-content"
              class="mb-4"
              method="post"
              hx-post="{{ url_for("home.rating_book", isbn=book.isbn) }}"
              hx-trigger="submit"
              hx-target="#model-content"
              hx-swap="innerHTML"
              hx-indicator="#spinner">
            <label class="form-control w-full max-w-xs mb-3.5 mt-2">
                <select name="rating" class="select select-bordered">
                    <option disabled selected>Pick one</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </label>
            <button class="btn btn-accent btn-sm" type="submit">
                Submit
            </button>
        </form>
        <div id="spinner" class="htmx-indicator absolute top-0 left-0 w-full h-full flex items-center justify-center">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"
             preserveAspectRatio="xMidYMid"
             style="shape-rendering: auto; display: block; background: rgb(255, 255, 255);" width="16"
             height="16"
             xmlns:xlink="http://www.w3.org/1999/xlink">
            <g>
                <g transform="translate(26.666666666666668,26.666666666666668)">
                    <rect fill="#e15b64" height="40" width="40" y="-20" x="-20">
                        <animateTransform begin="-0.3s" values="1.1500000000000001;1" keyTimes="0;1" dur="1s"
                                          repeatCount="indefinite" type="scale"
                                          attributeName="transform"></animateTransform>
                    </rect>
                </g>
                <g transform="translate(73.33333333333333,26.666666666666668)">
                    <rect fill="#f47e60" height="40" width="40" y="-20" x="-20">
                        <animateTransform begin="-0.2s" values="1.1500000000000001;1" keyTimes="0;1" dur="1s"
                                          repeatCount="indefinite" type="scale"
                                          attributeName="transform"></animateTransform>
                    </rect>
                </g>
                <g transform="translate(26.666666666666668,73.33333333333333)">
                    <rect fill="#f8b26a" height="40" width="40" y="-20" x="-20">
                        <animateTransform begin="0s" values="1.1500000000000001;1" keyTimes="0;1" dur="1s"
                                          repeatCount="indefinite" type="scale"
                                          attributeName="transform"></animateTransform>
                    </rect>
                </g>
                <g transform="translate(73.33333333333333,73.33333333333333)">
                    <rect fill="#abbd81" height="40" width="40" y="-20" x="-20">
                        <animateTransform begin="-0.1s" values="1.1500000000000001;1" keyTimes="0;1" dur="1s"
                                          repeatCount="indefinite" type="scale"
                                          attributeName="transform"></animateTransform>
                    </rect>
                </g>
                <g></g>
            </g>
        </svg>
        <style>
            .htmx-indicator {
                display: none;
                transition: opacity 500ms ease-in;
            }

            .htmx-request .htmx-indicator {
                display: flex;
            }

            .htmx-request.htmx-indicator {
                display: flex;
            }
        </style>
        </div>
    </div>
</dialog>

webapp/templates/components/rating_response.html
 <h3 class="font-bold text-lg">Thanks for your response!</h3>

webapp/templates/components/search_response_page.html
{% extends 'base.html' %}
{% block title %}Search{% endblock %}
{% block content %}
    {% include 'components/sub_navbar.html' %}
    {% include "components/search.html" %}
    <div class="bg-white">
        <div class="mx-auto max-w-2xl px-4 py-12 sm:px-6 lg:max-w-7xl lg:px-8">
            <div class="flex flex-row items-center justify-center pb-2 relative">
                <h2 class="text-md md:text-lg lg:text-xl flex-1 font-semibold">Search results</h2>
            </div>
            <div class="grid grid-cols-2 gap-x-6 gap-y-10 sm:grid-cols-4 xl:grid-cols-5 xl:gap-x-8">
            {% if (books is defined) and books %}
                {% for book in books %}
                    <a href="{{ url_for('home.book', isbn=book.isbn) }}" class="group">
                        <div class="relative w-full h-64 sm:h-72 overflow-hidden rounded-md bg-transparent border-gray-600 xl:aspect-h-8 xl:aspect-w-7">
                            <div class="absolute inset-0 bg-gray-200 opacity-40 group-hover:opacity-90"></div>
                            <img src="{{ book.img }}"
                                 alt="image"
                                 class="relative z-10 object-contain w-full h-full object-center pt-2 px-2 md:pt-6 md:px-4">
                        </div>
                        <h3 class="mt-4 text-base text-cyan-700 hover:underline hover:text-cyan-900 hover:cursor-pointer line-clamp-2">{{ book.title }}</h3>
                        <p class="mt-1 text-sm font-medium text-gray-900">by <i>{{ book.author }}</i></p>
                        <p class="mt-1 text-base font-medium text-gray-950">S${{ book.price }}</p>
                    </a>
                {% endfor %}
            {% else %}
            <p class="mt-1 text-sm font-medium text-gray-900">Nothing found, please try something else</p>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}