webapp/models/favourite_list.py
from sqlalchemy import PrimaryKeyConstraint
from .. import db


class FavouriteList(db.Model):
    __tablename__ = 'favourite_list'

    user_id = db.Column(db.String(250), db.ForeignKey('users.id', ondelete='CASCADE'))
    book_isbn = db.Column(db.String(30), db.ForeignKey('books.isbn', ondelete='CASCADE'))

    __table_args__ = (
        PrimaryKeyConstraint(
            user_id,
            book_isbn),
        {})

    cascade = "all, delete"

    def __init__(self, user_id, book_isbn):
        self.user_id = user_id
        self.book_isbn = book_isbn

webapp/views/accounts.py
from flask import Blueprint, flash, render_template, redirect, request, url_for, make_response
from flask_login import login_required, login_user, logout_user, current_user

from .. import bcrypt, db
from webapp.models.user_model import User
from webapp.form import LoginForm, RegisterForm
from ..models.book_model import Book
from ..models.favourite_list import FavouriteList

accounts_bp = Blueprint("accounts", __name__)


@accounts_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in.", "info")
        return redirect(url_for("home.home"))
    form = LoginForm(request.form)

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        user = User.query.filter_by(email=email).first()
        if user and bcrypt.check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for("home.home"))
        flash("Invalid email and/or password.", "danger")

    return render_template("accounts/login.html", form=form)


@accounts_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        flash("You are already registered.", "info")
        return redirect(url_for("home.home"))
    form = RegisterForm(request.form)

    if form.validate_on_submit():
        user = User(full_name=form.fullname.data, username=form.username.data,
                    email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()

        login_user(user)
        flash("You registered and are now logged in. Welcome!", "success")

        return redirect(url_for("home.home"))

    return render_template("accounts/register.html", form=form)


@accounts_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out.", "success")
    return redirect(url_for("accounts.login"))


@accounts_bp.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    is_logged_in = current_user.is_authenticated
    if is_logged_in:
        return render_template("accounts/user_profile.html", is_logged_in=is_logged_in, user=current_user)


@accounts_bp.route("/update-profile", methods=["GET", "PATCH"])
@login_required
def update_profile():
    is_logged_in = current_user.is_authenticated

    if request.method == "GET" and is_logged_in:
        edit_status = request.args.get("edit") == "true"
        name = request.args.get("name")
        if edit_status:
            return render_template("accounts/edit_form.html", user=current_user, name=name)

        return render_template("accounts/cancel_edit_form.html", user=current_user, name=name)

    if request.method == "PATCH" and is_logged_in:
        name = request.args.get("name")
        email = request.form.get("email")
        full_name = request.form.get("fullname")
        username = request.form.get("username")

        user = User.query.filter_by(id=current_user.id).first()

        email = email if email else user.email
        full_name = full_name if full_name else user.full_name
        username = username if username else user.username

        user.email = email
        user.full_name = full_name
        user.username = username

        db.session.commit()

        user = User.query.filter_by(id=current_user.id).first()
        return render_template("accounts/cancel_edit_form.html", user=user, name=name)


@accounts_bp.route("/favourite-list", methods=["GET"])
@login_required
def favourite_list():
    is_logged_in = current_user.is_authenticated
    if is_logged_in:
        book_isbn_list = FavouriteList.query.with_entities(FavouriteList.book_isbn).filter_by(user_id=current_user.id)
        fav_list = Book.query.filter(Book.isbn.in_(book_isbn_list)).all()
        subtotal = sum(book.price for book in fav_list)
        return render_template("accounts/favourite_list.html",
                               is_logged_in=is_logged_in,
                               favourite_list=fav_list,
                               subtotal_price=subtotal)
    return redirect(url_for("home.login"))


@accounts_bp.route("/add-to-favourite", methods=["POST"])
@login_required
def add_to_favourite():
    is_logged_in = current_user.is_authenticated
    if is_logged_in:
        book_isbn = request.args.get("isbn")
        existing_book_isbn = FavouriteList.query.filter_by(book_isbn=book_isbn).first()
        if existing_book_isbn is not None:
            success = False
            return render_template("accounts/add_to_favourite_response.html", success=success)
        fav_item = FavouriteList(user_id=current_user.id, book_isbn=book_isbn)
        db.session.add(fav_item)
        db.session.commit()
        success = True

        return render_template("accounts/add_to_favourite_response.html", success=success)
    return redirect(url_for("accounts.login"))


@accounts_bp.route("/delete-from-favorite/<string:isbn>", methods=["DELETE"])
@login_required
def delete_from_favourite(isbn):
    is_logged_in = current_user.is_authenticated
    if is_logged_in:
        FavouriteList.query.filter(FavouriteList.book_isbn == isbn).delete()
        db.session.commit()

        book_isbn_list = FavouriteList.query.with_entities(FavouriteList.book_isbn).filter_by(user_id=current_user.id)
        fav_list = Book.query.filter(Book.isbn.in_(book_isbn_list)).all()

        return render_template("accounts/favourite_list_inner.html", favourite_list=fav_list)

    return render_template("errors/400.html")


@accounts_bp.route("/favourite-list-summary", methods=["GET"])
@login_required
def favourite_list_summary():
    is_logged_in = current_user.is_authenticated
    if is_logged_in:
        # Query to fetch the list of ISBNs in the user's favorites.
        book_isbn_list = FavouriteList.query.with_entities(FavouriteList.book_isbn). \
            filter_by(user_id=current_user.id).all()
        isbn_list = [isbn for (isbn,) in book_isbn_list]
        # Query to get all books that are in the favorites list.
        if isbn_list:
            fav_list = Book.query.filter(Book.isbn.in_(isbn_list)).all()
        else:
            fav_list = []

        total_item = len(fav_list)
        total_price = sum(book.price for book in fav_list)

        html_content = render_template("accounts/favourite_list_summary.html",
                                       total_item=total_item, total_price=total_price)
        return html_content
    else:
        return render_template("errors/400.html"), 400

webapp/views/home.py
import pandas as pd
from flask import Blueprint, redirect, render_template, request, url_for, abort
from flask_login import current_user, login_required
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, LongType
from webapp import db
from webapp.models.book_model import Book, OpentrolleyBook, LazadaBook, NewArrival
import torch
from webapp.models.favourite_list import FavouriteList
from webapp.models.rating import Interaction, Rating
from webapp.models.review import Review
from webapp.models.user_model import User
from webapp.recommender.content_based_model import get_recommendations
from webapp.recommender.model import model, item_id_map, original_book_data, user_item_df, user_id_map
from webapp.recommender.utils import inference
from pyspark.ml.recommendation import ALS, ALSModel

home_bp = Blueprint("home", __name__)

spark = SparkSession.builder \
    .appName("Book Recommender") \
    .master("local[*]") \
    .config("spark.driver.memory", "1g") \
    .config("spark.driver.memoryOverhead", "512m") \
    .config("spark.memory.fraction", "0.8") \
    .config("spark.default.parallelism", "200") \
    .config("spark.sql.shuffle.partitions", "200") \
    .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer") \
    .getOrCreate()


@home_bp.route("/", methods=["GET"])
def home():
    if not current_user.is_authenticated:
        return redirect(url_for("home.landing_page"))

    if current_user.is_admin:
        return redirect(url_for("admin.admin"))

    page = request.args.get("page")
    sort_by = request.args.get("sort")
    if not page or not page.isdigit():
        return redirect(url_for("home.home", page=1))

    page = int(page)

    if sort_by == "newest":
        books = Book.query.order_by(Book.publication_year.desc()).limit(350).all()
    elif sort_by == "price-asc":
        books = Book.query.order_by(Book.price).limit(350).all()
    elif sort_by == "price-desc":
        books = Book.query.order_by(Book.price.desc()).limit(350).all()
    else:
        books = Book.query.order_by(Book.average_rating.desc()).limit(350).all()

    book_isbn_list = FavouriteList.query.with_entities(FavouriteList.book_isbn).filter_by(user_id=current_user.id)
    fav_list = Book.query.filter(Book.isbn.in_(book_isbn_list)).all()
    total_item = len(fav_list)
    total_price = sum([b.price for b in fav_list])

    books = books[(50 * page - 50): (50 * page)]

    return render_template(
        "home.html",
        is_logged_in=True,
        books=books,
        page=page,
        total_item=total_item,
        total_price=total_price,
        username=current_user.username
    )


@home_bp.route("/home", methods=["GET"])
def landing_page():
    new_arrivals = NewArrival.query.order_by(NewArrival.publication_year.desc()).limit(5).all()
    return render_template("components/landing_page.html", new_arrivals=new_arrivals)


@home_bp.route("/about", methods=["GET"])
def about():
    if current_user.is_authenticated:
        is_logged_in = current_user.is_authenticated
        username = current_user.username
        return render_template("about.html", is_logged_in=is_logged_in, username=username)
    return render_template("about.html", is_logged_in=False)


@home_bp.route("/book/<string:isbn>", methods=["GET"])
@login_required
def book(isbn):
    if not current_user.is_authenticated:
        return redirect(url_for("home.landing_page"))

    current_book = Book.query.filter(Book.isbn.in_([isbn])).first()
    if current_book is None:
        return render_template("errors/404.html")

    is_logged_in = True

    db_user_id = current_user.user_id
    user_id = torch.LongTensor([db_user_id])
    total_books = Book.query.count()

    # Million dollars recommender inference =))
    insert_interaction(current_user.id, isbn)

    # ratings = Rating.query.filter_by(user_id=current_user.id).all()
    book_exist_in_rating = Rating.query.filter_by(book_isbn=isbn, user_id=current_user.id).first()
    if book_exist_in_rating:
        rated = True
    else:
        rated = False

    current_user_id_in_df = user_id_map.get(db_user_id, 35)
    try:
        als_model = ALSModel.load(f"users/{current_user.user_id}/model.als")
    except Exception as e:
        print("Error loading the ALS model:", e)
        als_model = None
    recommend_books_als = None
    if als_model is not None:
        mylist = [{"user": current_user_id_in_df}]
        schema = StructType([
            StructField("user", LongType(), True)
        ])

        # Create the DataFrame using the list of dictionaries and the defined schema
        user_df = spark.createDataFrame(mylist, schema=schema)
        user_recs = als_model.recommendForUserSubset(user_df, 20)
        item_df = user_recs.selectExpr("user", "explode(recommendations) as rec")
        items = item_df.select("rec.item", "rec.rating")
        unique_items_list = [row['item'] for row in items.select("item").distinct().collect()]
        print(unique_items_list)
        top_k_books_isbn = original_book_data[original_book_data.book_id.isin(unique_items_list)]["isbn"].tolist()
        recommend_books_als = Book.query.filter(Book.isbn.in_(top_k_books_isbn)).all()

    updated_ratings = [0] * total_books

    # Query all interactions for the user
    interactions = Interaction.query.filter_by(user_id=current_user.id).all()
    # Get all ISBNs the user has interacted with
    interacted_isbns = [interaction.book_isbn for interaction in interactions]

    # Update ratings based on the interactions
    for i in interacted_isbns:
        if i in original_book_data['isbn'].values:
            book_id = original_book_data[original_book_data["isbn"] == i]["book_id"].to_list()
            if book_id:
                book_index = item_id_map.get(book_id[0], None)
                if book_index is not None:
                    updated_ratings[book_index] = 1

    user_ratings_tensor = torch.FloatTensor([updated_ratings])
    recommend_books = inference(
        model,
        user_id=user_id,
        user_ratings_tensor=user_ratings_tensor,
        item_id_map=item_id_map,
        apply_dropout=True,
    )

    recommend_books = Book.query.filter(Book.isbn.in_(recommend_books)).all()

    opentrolley_book = OpentrolleyBook.query.filter_by(isbn=current_book.isbn).first()
    lazada_book = LazadaBook.query.filter(LazadaBook.isbn.in_([isbn])).first()

    book_isbn_list = FavouriteList.query.with_entities(FavouriteList.book_isbn).filter_by(user_id=current_user.id)
    fav_list = Book.query.filter(Book.isbn.in_(book_isbn_list)).all()
    total_item = len(fav_list)
    total_price = sum([b.price for b in fav_list])

    reviews = (
        db.session.query(Review, User)
        .join(User, Review.user_id == User.id)
        .filter(Review.book_isbn == isbn)
        .all()
    )
    content_based_isbn_list = get_recommendations(current_book.title, 20)
    if content_based_isbn_list is None or len(content_based_isbn_list) is None:
        content_based_isbn_list = []
    similar_books = Book.query.filter(Book.isbn.in_(content_based_isbn_list)).all()
    return render_template("book_details.html",
                           book=current_book,
                           recommend_books=recommend_books,
                           similar_books=similar_books,
                           opentrolley_book=opentrolley_book,
                           lazada_book=lazada_book,
                           is_logged_in=is_logged_in,
                           total_item=total_item,
                           total_price=total_price, username=current_user.username,
                           reviews=reviews,
                           rated=rated,
                           recommend_books_als=recommend_books_als)


def insert_interaction(user_id, book_isbn):
    new_interaction = Interaction(user_id=user_id, book_isbn=book_isbn)
    db.session.add(new_interaction)
    try:
        db.session.commit()
        print("Data inserted successfully!")
    except Exception as e:
        db.session.rollback()
        print(f"An error occurred: {e}")


@home_bp.route("/rates/<string:isbn>", methods=["POST"])
@login_required
def rating_book(isbn):
    rating = request.form["rating"]
    rating = int(rating)
    new_rating = Rating(user_id=current_user.id, book_isbn=isbn, rating=rating)
    db.session.add(new_rating)
    try:
        current_user_id_in_df = user_id_map.get(current_user.user_id, 35)
        db.session.commit()
        print("Data inserted successfully!")
        # Check if the book is already rated by the user
        ratings = get_user_ratings(current_user.id)
        # Update user-item DataFrame only if necessary
        if len(ratings) % 5 == 0:
            # Query all interactions for the user
            # Get all ISBNs the user has interacted with
            interacted_isbns = [rating.book_isbn for rating in ratings]
            rating_values = [rating.rating for rating in ratings]

            # Update ratings based on the interactions
            books_id = []
            for isbn in interacted_isbns:
                if isbn in original_book_data['isbn'].values:
                    book_id = original_book_data[original_book_data["isbn"] == isbn]["book_id"].to_list()
                    if book_id:
                        book_index = item_id_map.get(book_id[0], None)
                        if book_index is not None:
                            books_id.append(book_index)
            new_user_ratings = {
                'user': [current_user_id_in_df] * len(rating_values),
                'item': books_id,
                'rating': rating_values
            }
            temp_df = user_item_df[user_item_df['user'] != current_user_id_in_df]

            updated_user_item_df = pd.concat([temp_df, pd.DataFrame(new_user_ratings)], ignore_index=True)
            updated_user_item_df['user'] = updated_user_item_df['user'].astype(int)

webapp/views/image.py
import base64
import io
import os
from PIL import Image
from flask import Blueprint, send_file, abort

image_bp = Blueprint('image', __name__)
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../'))


@image_bp.route('/images/<string:isbn>', methods=['GET'])
def get_image(isbn):
    # image = Image.open("./images/" + isbn + ".png")
    # data = io.BytesIO()
    # image.save(data, "PNG")
    # encoded_img_data = base64.b64encode(data.getvalue())
    # print(encoded_img_data)
    image_path = os.path.join(BASE_DIR, 'images', f'{isbn}.png')
    if not os.path.exists(image_path):
        abort(404)
    return send_file(image_path, mimetype='image/png')

webapp/templates/book_details.html
{% extends 'base.html' %}
{% block title %}Book{% endblock %}
{% block content %}
    {% include 'components/sub_navbar.html' %}
    {% include "components/search.html" %}
    <div id="display-successful-modal" class="absolute z-[100] left-1/2 -translate-x-1/2 -translate-y-1/2 m-auto top-32 w-1/2"></div>
    <div class="my-3.5 mx-5 md:mx-auto max-w-3xl py-12 lg:max-w-[1400px] lg:min-w-[1400px] lg:px-8">
        <div class="max-w-6xl mx-auto">
            <div class="flex flex-col md:flex-row -mx-4 md:gap-6 lg:gap-10">
                <div class="md:flex-1">
                    <div class="h-[460px] border-collapse border border-gray-200 shadow border-opacity-50 rounded px-3 py-6">
                        <img class="w-full h-full object-contain"
                             src="{{ url_for("image.get_image", isbn=book.isbn) }}"
                             alt="book image">
                    </div>
                </div>
                <div class="md:flex-1 md:px-4 px-10 lg:px-0">
                    <h2 class="text-2xl font-bold text-gray-800 lg:mt-0 mt-8 mb-2">{{ book.title }}</h2>
                    <p class="text-gray-600 text-sm mb-4">
                        by {{ book.author }} (Author)
                    </p>
                    {% include "components/rating.html" %}
                    <div class="my-4">
                    {% if not rated %}
                        {% include "components/rating_form.html" %}
                    {% endif %}
                    </div>
                    <div class="my-4">
                        <span class="font-semibold text-gray-700">Price:</span>
                        <span class="text-gray-600">S${{ book.price }}</span>
                    </div>
                    <div class="my-4">
                        <span class="font-semibold text-gray-700">Buy it from</span>
                        <a class="text-blue-500 underline hover:text-blue-600" href="{{ book.url }}" target="_blank">
                            Amazon
                            <i class="fa-solid fa-arrow-up-right-from-square fa-xs"></i>
                        </a>
                    </div>
                    <button class="btn bg-red-400 hover:bg-red-300"
                            hx-trigger="click"
                            hx-post="{{ url_for("accounts.add_to_favourite", isbn=book.isbn) }}"
                            hx-target="#display-successful-modal"
                            hx-swap="innerHTML"
                    >
                        Add to favorite
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                             stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                  d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
                        </svg>
                    </button>
                    <button class="btn btn-outline btn-info">
                        <a href="#compare-price">Compare price</a>
                    </button>
                    <h2 class="mt-10 font-semibold">Description</h2>
                    <div class="flex -mx-6" x-data="texts()">
                        <template x-for="(text, index) in texts">
                            <div class="max-w-prose mx-auto p-6 relative">
                                <p class="text-sm md:text-[15px] text-justify text-gray-700 line-clamp-4" x-text="text"
                                   x-init="$nextTick(() => { setTruncate(index, $el) })">
                                </p>

                                <!-- dont show read more / read less if the text is not truncated -->
                                <template class="absolute bottom-0 left-0 right-0 px-6 py-4 bg-white w-full"
                                          x-if="truncatable[index]">
                                    <div>
                                        <button class="my-4 underline text-blue-500"
                                                @click="event.target.parentNode.parentNode.querySelector('p').classList.remove('line-clamp-4'); truncated[index] = false;"
                                                x-show="truncated[index]">Read more...
                                        </button>

                                        <button class="my-4 underline text-blue-500"
                                                @click="event.target.parentNode.parentNode.querySelector('p').classList.add('line-clamp-4'); truncated[index] = true;"
                                                x-show="!truncated[index]">Read less...
                                        </button>
                                    </div>
                                </template>
                            </div>
                        </template>
                        <script>
                            function texts() {
                                return {
                                    truncated: [false, false],
                                    truncatable: [false, false],
                                    texts: [
                                        "{{ book.description | safe }}"
                                    ],
                                    setTruncate(index, element) {
                                        if (element.offsetHeight < element.scrollHeight ||
                                            element.offsetWidth < element.scrollWidth) {
                                            // your element has an overflow
                                            // show read more button
                                            this.truncated[index] = true;
                                            this.truncatable[index] = true;
                                        } else {
                                            // your element doesn't have overflow
                                            this.truncated[index] = false;
                                            this.truncatable[index] = false;
                                        }
                                    },
                                    isTruncated(index) {
                                        return true;
                                    }
                                }
                            }
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include "components/compare_price.html" %}

    <div class="mx-auto max-w-3xl py-12 lg:max-w-[1400px] lg:px-8">
        <h1 class="text-lg font-bold pb-4">Customers who viewed this item also viewed</h1>
        <div class="flex flex-row items-center justify-center space-x-4 overflow-hidden w-full">
            <button onclick="scrollCarousel(-5)"
                    class="hidden sm:block bg-gray-200 hover:bg-gray-300 text-gray-800 font-bold py-2 px-4 rounded focus:outline-none">
                &#8592;
            </button>

            <div id="carousel"
                 class="flex flex-row space-x-1 gap-12 md:gap-0 overflow-x-auto lg:overflow-x-hidden scroll-smooth">
                {% for book in recommend_books %}
                    <div class="flex-none w-1/3 md:w-1/5 ">
                        <a href="{{ url_for('home.book', isbn=book.isbn) }}" class="group">
                            <div class="rounded-md bg-slate-100 w-52 h-64">
                                <img src="{{ book.img }}" alt="image"
                                     class="relative z-10 object-contain w-full h-full object-center pt-2 px-2 md:pt-6">
                            </div>
                            <h3 class="mt-4 text-base text-cyan-700 hover:underline hover:text-cyan-900 hover:cursor-pointer line-clamp-2">{{ book.title }}</h3>
                            <p class="mt-1 text-sm font-medium text-gray-900">by <i>{{ book.author }}</i></p>
                            <p class="mt-1 text-base font-medium text-gray-950">{{ book.price }}</p>
                        </a>
                    </div>
                {% endfor %}
            </div>
            <style>
                ::-webkit-scrollbar {
                    height: 4px; /* height of horizontal scrollbar ← You're missing this */
                    width: 4px; /* width of vertical scrollbar */
                    border: 1px solid #7b7b7b;
                }
            </style>
            <button onclick="scrollCarousel(5)"
                    class="hidden sm:block bg-gray-200 hover:bg-gray-300 text-gray-800 font-bold py-2 px-4 rounded focus:outline-none">
                &#8594;
            </button>
        </div>
    </div>
    
    {% if similar_books is defined and similar_books|length > 0 %}
    <div class="mx-auto max-w-3xl py-12 lg:max-w-[1400px] lg:px-8">
        <h1 class="text-lg font-bold pb-4">Similar Books</h1>
        <div class="flex flex-row items-center justify-center space-x-4 overflow-hidden w-full">
            <button onclick="scrollCarousel2(-5)"
                    class="hidden sm:block bg-gray-200 hover:bg-gray-300 text-gray-800 font-bold py-2 px-4 rounded focus:outline-none">
                &#8592;
            </button>

            <div id="carousel-2"
                 class="flex flex-row space-x-1 gap-12 md:gap-0 overflow-x-auto lg:overflow-x-hidden scroll-smooth">
                {% for book in similar_books %}
                    <div class="flex-none w-1/3 md:w-1/5 ">
                        <a href="{{ url_for('home.book', isbn=book.isbn) }}" class="group">
                            <div class="rounded-md bg-slate-100 w-52 h-64">
                                <img src="{{ book.img }}" alt="image"
                                     class="relative z-10 object-contain w-full h-full object-center pt-2 px-2 md:pt-6">
                            </div>
                            <h3 class="mt-4 text-base text-cyan-700 hover:underline hover:text-cyan-900 hover:cursor-pointer line-clamp-2">{{ book.title }}</h3>
                            <p class="mt-1 text-sm font-medium text-gray-900">by <i>{{ book.author }}</i></p>
                            <p class="mt-1 text-base font-medium text-gray-950">{{ book.price }}</p>
                        </a>
                    </div>
                {% endfor %}
            </div>
            <style>
                ::-webkit-scrollbar {
                    height: 4px; /* height of horizontal scrollbar ← You're missing this */
                    width: 4px; /* width of vertical scrollbar */
                    border: 1px solid #7b7b7b;
                }
            </style>
            <button onclick="scrollCarousel2(5)"
                    class="hidden sm:block bg-gray-200 hover:bg-gray-300 text-gray-800 font-bold py-2 px-4 rounded focus:outline-none">
                &#8594;
            </button>
        </div>
    </div>
    {% endif %}
    {% include "components/recommend_als.html" %}
    {% include "components/customer_reviews.html" %}
    <script>
        let carousel = document.getElementById('carousel');
        let carouselWidth = carousel.offsetWidth;
        let itemWidth = carousel.children[0].offsetWidth;
        let numItems = carousel.children.length;
        let currentIndex = 0;

        function scrollCarousel(direction) {
            let newIndex = currentIndex + direction;
            if (newIndex < 0) {
                newIndex = 0;
            } else if (newIndex >= numItems - 4) {
                newIndex = numItems - 5;
            }
            carousel.scrollLeft = newIndex * (itemWidth + 3);
            currentIndex = newIndex;
        }

        let carousel2 = document.getElementById('carousel-2');
        let carouselWidth2 = carousel.offsetWidth;
        let itemWidth2 = carousel2.children[0].offsetWidth;
        let numItems2 = carousel2.children.length;
        let currentIndex2 = 0;

        function scrollCarousel2(direction) {
            let newIndex = currentIndex2 + direction;
            if (newIndex < 0) {
                newIndex = 0;
            } else if (newIndex >= numItems2 - 4) {
                newIndex = numItems2 - 5;
            }
            carousel2.scrollLeft = newIndex * (itemWidth2 + 3);
            currentIndex2 = newIndex;
        }
    </script>
    <style>
        #carousel::-webkit-scrollbar {
            display: none;
        }

        #carousel {
            -ms-overflow-style: none;
            scrollbar-width: none;
        }

        #carousel-2::-webkit-scrollbar {
            display: none;
        }

        #carousel-2 {
            -ms-overflow-style: none;
            scrollbar-width: none;
        }
    </style>
{% endblock %}

webapp/templates/home.html
{% extends 'base.html' %}
{% block title %}OtakuOasis{% endblock %}
{% block content %}
    {% include 'components/sub_navbar.html' %}
    {% include "components/search.html" %}
    {% include "components/products.html" %}
    {% include "components/pagination.html" %}
{% endblock %}