webapp/models/favourite_list.py
from sqlalchemy import PrimaryKeyConstraint
from .. import db


class FavouriteList(db.Model):
    __tablename__ = 'favourite_list'

    user_id = db.Column(db.String(250), db.ForeignKey('users.id', ondelete='CASCADE'))
    book_isbn = db.Column(db.String(30), db.ForeignKey('books.isbn', ondelete='CASCADE'))

    __table_args__ = (
        PrimaryKeyConstraint(
            user_id,
            book_isbn),
        {})

    cascade = "all, delete"

    def __init__(self, user_id, book_isbn):
        self.user_id = user_id
        self.book_isbn = book_isbn

webapp/views/accounts.py
from flask import Blueprint, flash, render_template, redirect, request, url_for, make_response
from flask_login import login_required, login_user, logout_user, current_user

from .. import bcrypt, db
from webapp.models.user_model import User
from webapp.form import LoginForm, RegisterForm
from ..models.book_model import Book
from ..models.favourite_list import FavouriteList

accounts_bp = Blueprint("accounts", __name__)


@accounts_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in.", "info")
        return redirect(url_for("home.home"))
    form = LoginForm(request.form)

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        user = User.query.filter_by(email=email).first()
        if user and bcrypt.check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for("home.home"))
        flash("Invalid email and/or password.", "danger")

    return render_template("accounts/login.html", form=form)


@accounts_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        flash("You are already registered.", "info")
        return redirect(url_for("home.home"))
    form = RegisterForm(request.form)

    if form.validate_on_submit():
        user = User(full_name=form.fullname.data, username=form.username.data,
                    email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()

        login_user(user)
        flash("You registered and are now logged in. Welcome!", "success")

        return redirect(url_for("home.home"))

    return render_template("accounts/register.html", form=form)


@accounts_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out.", "success")
    return redirect(url_for("accounts.login"))


@accounts_bp.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    is_logged_in = current_user.is_authenticated
    if is_logged_in:
        return render_template("accounts/user_profile.html", is_logged_in=is_logged_in, user=current_user)


@accounts_bp.route("/update-profile", methods=["GET", "PATCH"])
@login_required
def update_profile():
    is_logged_in = current_user.is_authenticated

    if request.method == "GET" and is_logged_in:
        edit_status = request.args.get("edit") == "true"
        name = request.args.get("name")
        if edit_status:
            return render_template("accounts/edit_form.html", user=current_user, name=name)

        return render_template("accounts/cancel_edit_form.html", user=current_user, name=name)

    if request.method == "PATCH" and is_logged_in:
        name = request.args.get("name")
        email = request.form.get("email")
        full_name = request.form.get("fullname")
        username = request.form.get("username")

        user = User.query.filter_by(id=current_user.id).first()

        email = email if email else user.email
        full_name = full_name if full_name else user.full_name
        username = username if username else user.username

        user.email = email
        user.full_name = full_name
        user.username = username

        db.session.commit()

        user = User.query.filter_by(id=current_user.id).first()
        return render_template("accounts/cancel_edit_form.html", user=user, name=name)


@accounts_bp.route("/favourite-list", methods=["GET"])
@login_required
def favourite_list():
    is_logged_in = current_user.is_authenticated
    if is_logged_in:
        book_isbn_list = FavouriteList.query.with_entities(FavouriteList.book_isbn).filter_by(user_id=current_user.id)
        fav_list = Book.query.filter(Book.isbn.in_(book_isbn_list)).all()
        subtotal = sum(book.price for book in fav_list)
        return render_template("accounts/favourite_list.html",
                               is_logged_in=is_logged_in,
                               favourite_list=fav_list,
                               subtotal_price=subtotal)
    return redirect(url_for("home.login"))


@accounts_bp.route("/add-to-favourite", methods=["POST"])
@login_required
def add_to_favourite():
    is_logged_in = current_user.is_authenticated
    if is_logged_in:
        book_isbn = request.args.get("isbn")
        existing_book_isbn = FavouriteList.query.filter_by(book_isbn=book_isbn).first()
        if existing_book_isbn is not None:
            success = False
            return render_template("accounts/add_to_favourite_response.html", success=success)
        fav_item = FavouriteList(user_id=current_user.id, book_isbn=book_isbn)
        db.session.add(fav_item)
        db.session.commit()
        success = True

        return render_template("accounts/add_to_favourite_response.html", success=success)
    return redirect(url_for("accounts.login"))


@accounts_bp.route("/delete-from-favorite/<string:isbn>", methods=["DELETE"])
@login_required
def delete_from_favourite(isbn):
    is_logged_in = current_user.is_authenticated
    if is_logged_in:
        FavouriteList.query.filter(FavouriteList.book_isbn == isbn).delete()
        db.session.commit()

        book_isbn_list = FavouriteList.query.with_entities(FavouriteList.book_isbn).filter_by(user_id=current_user.id)
        fav_list = Book.query.filter(Book.isbn.in_(book_isbn_list)).all()

        return render_template("accounts/favourite_list_inner.html", favourite_list=fav_list)

    return render_template("errors/400.html")


@accounts_bp.route("/favourite-list-summary", methods=["GET"])
@login_required
def favourite_list_summary():
    is_logged_in = current_user.is_authenticated
    if is_logged_in:
        # Query to fetch the list of ISBNs in the user's favorites.
        book_isbn_list = FavouriteList.query.with_entities(FavouriteList.book_isbn). \
            filter_by(user_id=current_user.id).all()
        isbn_list = [isbn for (isbn,) in book_isbn_list]
        # Query to get all books that are in the favorites list.
        if isbn_list:
            fav_list = Book.query.filter(Book.isbn.in_(isbn_list)).all()
        else:
            fav_list = []

        total_item = len(fav_list)
        total_price = sum(book.price for book in fav_list)

        html_content = render_template("accounts/favourite_list_summary.html",
                                       total_item=total_item, total_price=total_price)
        return html_content
    else:
        return render_template("errors/400.html"), 400

webapp/views/home.py
import pandas as pd
from flask import Blueprint, redirect, render_template, request, url_for, abort
from flask_login import current_user, login_required
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, LongType
from webapp import db
from webapp.models.book_model import Book, OpentrolleyBook, LazadaBook, NewArrival
import torch
from webapp.models.favourite_list import FavouriteList
from webapp.models.rating import Interaction, Rating
from webapp.models.review import Review
from webapp.models.user_model import User
from webapp.recommender.content_based_model import get_recommendations
from webapp.recommender.model import model, item_id_map, original_book_data, user_item_df, user_id_map
from webapp.recommender.utils import inference
from pyspark.ml.recommendation import ALS, ALSModel

home_bp = Blueprint("home", __name__)

spark = SparkSession.builder \
    .appName("Book Recommender") \
    .master("local[*]") \
    .config("spark.driver.memory", "1g") \
    .config("spark.driver.memoryOverhead", "512m") \
    .config("spark.memory.fraction", "0.8") \
    .config("spark.default.parallelism", "200") \
    .config("spark.sql.shuffle.partitions", "200") \
    .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer") \
    .getOrCreate()


@home_bp.route("/", methods=["GET"])
def home():
    if not current_user.is_authenticated:
        return redirect(url_for("home.landing_page"))

    if current_user.is_admin:
        return redirect(url_for("admin.admin"))

    page = request.args.get("page")
    sort_by = request.args.get("sort")
    if not page or not page.isdigit():
        return redirect(url_for("home.home", page=1))

    page = int(page)

    if sort_by == "newest":
        books = Book.query.order_by(Book.publication_year.desc()).limit(350).all()
    elif sort_by == "price-asc":
        books = Book.query.order_by(Book.price).limit(350).all()
    elif sort_by == "price-desc":
        books = Book.query.order_by(Book.price.desc()).limit(350).all()
    else:
        books = Book.query.order_by(Book.average_rating.desc()).limit(350).all()

    book_isbn_list = FavouriteList.query.with_entities(FavouriteList.book_isbn).filter_by(user_id=current_user.id)
    fav_list = Book.query.filter(Book.isbn.in_(book_isbn_list)).all()
    total_item = len(fav_list)
    total_price = sum([b.price for b in fav_list])

    books = books[(50 * page - 50): (50 * page)]

    return render_template(
        "home.html",
        is_logged_in=True,
        books=books,
        page=page,
        total_item=total_item,
        total_price=total_price,
        username=current_user.username
    )


@home_bp.route("/home", methods=["GET"])
def landing_page():
    new_arrivals = NewArrival.query.order_by(NewArrival.publication_year.desc()).limit(5).all()
    return render_template("components/landing_page.html", new_arrivals=new_arrivals)


@home_bp.route("/about", methods=["GET"])
def about():
    if current_user.is_authenticated:
        is_logged_in = current_user.is_authenticated
        username = current_user.username
        return render_template("about.html", is_logged_in=is_logged_in, username=username)
    return render_template("about.html", is_logged_in=False)


@home_bp.route("/book/<string:isbn>", methods=["GET"])
@login_required
def book(isbn):
    if not current_user.is_authenticated:
        return redirect(url_for("home.landing_page"))

    current_book = Book.query.filter(Book.isbn.in_([isbn])).first()
    if current_book is None:
        return render_template("errors/404.html")

    is_logged_in = True

    db_user_id = current_user.user_id
    user_id = torch.LongTensor([db_user_id])
    total_books = Book.query.count()

    # Million dollars recommender inference =))
    insert_interaction(current_user.id, isbn)

    # ratings = Rating.query.filter_by(user_id=current_user.id).all()
    book_exist_in_rating = Rating.query.filter_by(book_isbn=isbn, user_id=current_user.id).first()
    if book_exist_in_rating:
        rated = True
    else:
        rated = False

    current_user_id_in_df = user_id_map.get(db_user_id, 35)
    try:
        als_model = ALSModel.load(f"users/{current_user.user_id}/model.als")
    except Exception as e:
        print("Error loading the ALS model:", e)
        als_model = None
    recommend_books_als = None
    if als_model is not None:
        mylist = [{"user": current_user_id_in_df}]
        schema = StructType([
            StructField("user", LongType(), True)
        ])

        # Create the DataFrame using the list of dictionaries and the defined schema
        user_df = spark.createDataFrame(mylist, schema=schema)
        user_recs = als_model.recommendForUserSubset(user_df, 20)
        item_df = user_recs.selectExpr("user", "explode(recommendations) as rec")
        items = item_df.select("rec.item", "rec.rating")
        unique_items_list = [row['item'] for row in items.select("item").distinct().collect()]
        print(unique_items_list)
        top_k_books_isbn = original_book_data[original_book_data.book_id.isin(unique_items_list)]["isbn"].tolist()
        recommend_books_als = Book.query.filter(Book.isbn.in_(top_k_books_isbn)).all()

    updated_ratings = [0] * total_books

    # Query all interactions for the user
    interactions = Interaction.query.filter_by(user_id=current_user.id).all()
    # Get all ISBNs the user has interacted with
    interacted_isbns = [interaction.book_isbn for interaction in interactions]

    # Update ratings based on the interactions
    for i in interacted_isbns:
        if i in original_book_data['isbn'].values:
            book_id = original_book_data[original_book_data["isbn"] == i]["book_id"].to_list()
            if book_id:
                book_index = item_id_map.get(book_id[0], None)
                if book_index is not None:
                    updated_ratings[book_index] = 1

    user_ratings_tensor = torch.FloatTensor([updated_ratings])
    recommend_books = inference(
        model,
        user_id=user_id,
        user_ratings_tensor=user_ratings_tensor,
        item_id_map=item_id_map,
        apply_dropout=True,
    )

    recommend_books = Book.query.filter(Book.isbn.in_(recommend_books)).all()

    opentrolley_book = OpentrolleyBook.query.filter_by(isbn=current_book.isbn).first()
    lazada_book = LazadaBook.query.filter(LazadaBook.isbn.in_([isbn])).first()

    book_isbn_list = FavouriteList.query.with_entities(FavouriteList.book_isbn).filter_by(user_id=current_user.id)
    fav_list = Book.query.filter(Book.isbn.in_(book_isbn_list)).all()
    total_item = len(fav_list)
    total_price = sum([b.price for b in fav_list])

    reviews = (
        db.session.query(Review, User)
        .join(User, Review.user_id == User.id)
        .filter(Review.book_isbn == isbn)
        .all()
    )
    content_based_isbn_list = get_recommendations(current_book.title, 20)
    if content_based_isbn_list is None or len(content_based_isbn_list) is None:
        content_based_isbn_list = []
    similar_books = Book.query.filter(Book.isbn.in_(content_based_isbn_list)).all()
    return render_template("book_details.html",
                           book=current_book,
                           recommend_books=recommend_books,
                           similar_books=similar_books,
                           opentrolley_book=opentrolley_book,
                           lazada_book=lazada_book,
                           is_logged_in=is_logged_in,
                           total_item=total_item,
                           total_price=total_price, username=current_user.username,
                           reviews=reviews,
                           rated=rated,
                           recommend_books_als=recommend_books_als)


def insert_interaction(user_id, book_isbn):
    new_interaction = Interaction(user_id=user_id, book_isbn=book_isbn)
    db.session.add(new_interaction)
    try:
        db.session.commit()
        print("Data inserted successfully!")
    except Exception as e:
        db.session.rollback()
        print(f"An error occurred: {e}")


@home_bp.route("/rates/<string:isbn>", methods=["POST"])
@login_required
def rating_book(isbn):
    rating = request.form["rating"]
    rating = int(rating)
    new_rating = Rating(user_id=current_user.id, book_isbn=isbn, rating=rating)
    db.session.add(new_rating)
    try:
        current_user_id_in_df = user_id_map.get(current_user.user_id, 35)
        db.session.commit()
        print("Data inserted successfully!")
        # Check if the book is already rated by the user
        ratings = get_user_ratings(current_user.id)
        # Update user-item DataFrame only if necessary
        if len(ratings) % 5 == 0:
            # Query all interactions for the user
            # Get all ISBNs the user has interacted with
            interacted_isbns = [rating.book_isbn for rating in ratings]
            rating_values = [rating.rating for rating in ratings]

            # Update ratings based on the interactions
            books_id = []
            for isbn in interacted_isbns:
                if isbn in original_book_data['isbn'].values:
                    book_id = original_book_data[original_book_data["isbn"] == isbn]["book_id"].to_list()
                    if book_id:
                        book_index = item_id_map.get(book_id[0], None)
                        if book_index is not None:
                            books_id.append(book_index)
            new_user_ratings = {
                'user': [current_user_id_in_df] * len(rating_values),
                'item': books_id,
                'rating': rating_values
            }
            temp_df = user_item_df[user_item_df['user'] != current_user_id_in_df]

            updated_user_item_df = pd.concat([temp_df, pd.DataFrame(new_user_ratings)], ignore_index=True)
            updated_user_item_df['user'] = updated_user_item_df['user'].astype(int)

webapp/views/image.py
import base64
import io
import os
from PIL import Image
from flask import Blueprint, send_file, abort

image_bp = Blueprint('image', __name__)
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../'))


@image_bp.route('/images/<string:isbn>', methods=['GET'])
def get_image(isbn):
    # image = Image.open("./images/" + isbn + ".png")
    # data = io.BytesIO()
    # image.save(data, "PNG")
    # encoded_img_data = base64.b64encode(data.getvalue())
    # print(encoded_img_data)
    image_path = os.path.join(BASE_DIR, 'images', f'{isbn}.png')
    if not os.path.exists(image_path):
        abort(404)
    return send_file(image_path, mimetype='image/png')

webapp/templates/accounts/cancel_edit_form.html
{% if name == "email" %}
        <div class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 flex flex-row justify-between gap-4 items-center" id="open-edit-form-1">
            Email:
            <span class="flex-1" id="email">{{ user.email }}</span>
            <button hx-get="{{ url_for("accounts.update_profile", edit="true", name="email") }}"
                    hx-target="#open-edit-form-1"
                    hx-swap="outerHTML"
            >
                <i class="fa-regular fa-pen-to-square text-blue-700 hover:scale-125"></i>
            </button>
        </div>
{% elif name == "fullname" %}
        <div class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 flex flex-row justify-between gap-4 items-center" id="open-edit-form-2">
            Full name:
            <span class="flex-1" id="email">{{ user.full_name }}</span>
            <button hx-get="{{ url_for("accounts.update_profile", edit="true", name="fullname") }}"
                    hx-target="#open-edit-form-2"
                    hx-swap="outerHTML"
            >
                <i class="fa-regular fa-pen-to-square text-blue-700 hover:scale-125"></i>
            </button>
        </div>
{% else %}
        <div class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 flex flex-row justify-between gap-4 items-center" id="open-edit-form-3">
            Username:
            <span class="flex-1" id="email">{{ user.username }}</span>
            <button hx-get="{{ url_for("accounts.update_profile", edit="true", name="username") }}"
                    hx-target="#open-edit-form-3"
                    hx-swap="outerHTML"
            >
                <i class="fa-regular fa-pen-to-square text-blue-700 hover:scale-125"></i>
            </button>
        </div>
{% endif %}

webapp/templates/accounts/edit_form.html
<form class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 flex
flex-row justify-between gap-4 items-center"
     id="close-edit-form">
    {% if name == "email" %}
        Email:
        <div class="relative h-10 w-full min-w-[150px]">
            <label>
                <input
                        name="email"
                        type="text"
                        placeholder=""
                        class="peer h-full w-full
                          rounded-md border border-blue-gray-300
                          !border-t-blue-gray-200 bg-transparent px-3 py-3 font-sans text-sm font-normal text-blue-gray-700
                          outline outline-0 transition-all placeholder-shown:border placeholder-shown:border-blue-gray-200
                          placeholder-shown:border-t-blue-gray-200 focus:border-2 focus:border-blue-700 focus:border-t-transparent
                          focus:!border-t-blue-700 focus:outline-0"
                        value="{{ user.email }}"
                />
            </label>
        </div>
        <button type="submit" 
                hx-patch="{{ url_for("accounts.update_profile", name="email") }}"
                hx-target="#close-edit-form"
                hx-swap="outerHTML"
                >
            <i class="fa-solid fa-square-check text-green-500 hover:scale-125 text-xl"></i>
        </button>
        <button hx-get="{{ url_for("accounts.update_profile", edit="false", name="email") }}"
                hx-target="#close-edit-form"
                hx-swap="outerHTML"
        >
            <i class="fa-sharp fa-solid fa-xmark text-red-700 hover:scale-125 text-xl"></i>
        </button>
    {% elif name == "fullname" %}
        Full Name:
        <div class="relative h-10 w-full min-w-[150px]">
            <label>
                <input
                        name="fullname"
                        type="text"
                        placeholder=""
                        class="peer h-full w-full
                          rounded-md border border-blue-gray-300
                          !border-t-blue-gray-200 bg-transparent px-3 py-3 font-sans text-sm font-normal text-blue-gray-700
                          outline outline-0 transition-all placeholder-shown:border placeholder-shown:border-blue-gray-200
                          placeholder-shown:border-t-blue-gray-200 focus:border-2 focus:border-blue-700 focus:border-t-transparent
                          focus:!border-t-blue-700 focus:outline-0"
                        value="{{ user.full_name }}"
                />
            </label>
        </div>
        <button type="submit" 
                hx-patch="{{ url_for("accounts.update_profile", name="fullname") }}"
                hx-target="#close-edit-form"
                hx-swap="outerHTML"
        >
            <i class="fa-solid fa-square-check text-green-500 hover:scale-125 text-xl"></i>
        </button>
        <button hx-get="{{ url_for("accounts.update_profile", edit="false", name="fullname") }}"
                hx-target="#close-edit-form"
                hx-swap="outerHTML"
        >
            <i class="fa-sharp fa-solid fa-xmark text-red-700 hover:scale-125 text-xl"></i>
        </button>
    {% else %}
        Username:
        <div class="relative h-10 w-full min-w-[150px]">
            <label>
                <input
                        name="username"
                        type="text"
                        placeholder=""
                        class="peer h-full w-full
                          rounded-md border border-blue-gray-300
                          !border-t-blue-gray-200 bg-transparent px-3 py-3 font-sans text-sm font-normal text-blue-gray-700
                          outline outline-0 transition-all placeholder-shown:border placeholder-shown:border-blue-gray-200
                          placeholder-shown:border-t-blue-gray-200 focus:border-2 focus:border-blue-700 focus:border-t-transparent
                          focus:!border-t-blue-700 focus:outline-0"
                        value="{{ user.username }}"
                />
            </label>
        </div>
        <button type="submit" 
                hx-patch="{{ url_for("accounts.update_profile", name="username") }}"
                hx-target="#close-edit-form"
                hx-swap="outerHTML"
        >
            <i class="fa-solid fa-square-check text-green-500 hover:scale-125 text-xl"></i>
        </button>
        <button hx-get="{{ url_for("accounts.update_profile", edit="false", name="username") }}"
                hx-target="#close-edit-form"
                hx-swap="outerHTML"
        >
            <i class="fa-sharp fa-solid fa-xmark text-red-700 hover:scale-125 text-xl"></i>
        </button>
    {% endif %}
</form>

webapp/templates/accounts/favourite_list.html
{% extends 'base.html' %}
{% block title %}Book{% endblock %}
{% block content %}
    {% include 'components/sub_navbar.html' %}
    <div class="h-screen">
        <div class="py-12">
            <div class="max-w-md mx-auto shadow-lg border-2 border-t-gray-300 rounded-lg  md:max-w-5xl">
                <div class="md:flex ">
                    <div class="w-full p-4 px-5 py-5">
                        <div class="grid grid-cols-1 md:grid md:grid-cols-2 gap-2 ">
                            <div class="col-span-1 md:col-span-2 p-5" id="favourite-list">
                                <h1 class="text-xl font-medium text-center">Favourite List</h1>
                                {% if favourite_list is defined and favourite_list|length > 0 %}
                                    {% for book in favourite_list %}
                                        <div class="flex flex-col md:flex-row justify-between  items-center mt-6 pt-6 ">
                                            <div class="flex items-center">
                                                <img src="{{ book.img }}" width="60" alt="{{ book.title }}">
                                                <div class="flex flex-col ml-3">
                                                    <a class="md:text-[16px] font-medium hover:text-blue-600 hover:underline cursor-pointer text-clip"
                                                       href="{{ url_for('home.book', isbn=book.isbn) }}">{{ book.title }}</a>
                                                </div>
                                            </div>
                                            <div class="flex justify-center items-center">
                                                <div class="pr-8">
                                                    <span class="text-sm font-medium">S${{ book.price }}</span>
                                                </div>
                                                <div>
                                                <span class="text-sm text-red-500 hover:underline cursor-pointer"
                                                      hx-delete="{{ url_for("accounts.delete_from_favourite", isbn=book.isbn) }}"
                                                      hx-trigger="click"
                                                      hx-target="#favourite-list"
                                                      hx-swap="innerHTML"
                                                >DELETE</span>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                    <div class="flex justify-between items-center mt-6 pt-6 border-t">
                                        <div class="flex items-center">
                                            <i class="fa fa-arrow-left text-xs text-blue-500 pr-2"></i>
                                            <a class="text-md text-blue-500 hover:underline hover:text-blue-600"
                                               href="{{ url_for("home.home") }}">
                                                Back to home</a>
                                        </div>
                                        <div class="flex justify-center items-end">
                                            <span class="text-[14px] text-gray-400 mr-1">Subtotal:</span>
                                            <span class="text-[15px] font-medium text-gray-700 items-center">S${{ subtotal_price }}</span>
                                        </div>
                                    </div>
                                {% else %}
                                    <div class="flex justify-between items-center mt-6 pt-6">
                                        <span>List is empty, please add books to see.</span>
                                    </div>
                                    <div class="flex justify-between items-center mt-6 pt-6 border-t">
                                        <div class="flex items-center">
                                            <i class="fa fa-arrow-left text-xs text-blue-500 pr-2"></i>
                                            <a class="text-md text-blue-500 hover:underline hover:text-blue-600"
                                               href="{{ url_for("home.home") }}">
                                                Back to home</a>
                                        </div>
                                        <div class="flex justify-center items-end">
                                            <span class="text-[14px] text-gray-400 mr-1">Subtotal:</span>
                                            <span class="text-[15px] font-medium text-gray-700 items-center">S$0</span>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

webapp/templates/accounts/favourite_list_inner.html
<h1 class="text-xl font-medium text-center">Favourite List</h1>
{% if favourite_list is defined and favourite_list|length > 0 %}
{% for book in favourite_list %}
    <div class="flex justify-between items-center mt-6 pt-6">
        <div class="flex items-center">
            <img src="{{ book.img }}" width="60" alt="{{ book.title }}">
            <div class="flex flex-col ml-3">
                <span class="md:text-md font-medium">{{ book.title }}</span>
            </div>
        </div>

        <div class="flex justify-center items-center">
            <div class="pr-8 ">
                <span class="text-sm font-medium">S${{ book.price }}</span>
            </div>
            <div>
                <span class="text-sm text-red-500 hover:underline cursor-pointer"
                      hx-delete="{{ url_for("accounts.delete_from_favourite", isbn=book.isbn) }}"
                      hx-trigger="click"
                      hx-target="#favourite-list"
                      hx-swap="innerHTML"
                >DELETE</span>
            </div>
        </div>
    </div>
{% endfor %}
{% else %}
    <div class="flex justify-between items-center mt-6 pt-6">
        <span>List is empty, please add books to see.</span>
    </div>
{% endif %}
<div class="flex justify-between items-center mt-6 pt-6 border-t">
    <div class="flex items-center">
        <i class="fa fa-arrow-left text-xs text-blue-500 pr-2"></i>
        <a class="text-md text-blue-500 hover:underline hover:text-blue-600" href="{{ url_for("home.home") }}">
            Back to home</a>
    </div>
    <div class="flex justify-center items-end">
        <span class="text-[15px] font-medium text-gray-400 mr-1">Subtotal:</span>
        <span class="text-[15px] font-medium text-gray-700 items-center">S$0</span>
    </div>
</div>